site_name: KCEO Glossary
site_url: https://do-me.github.io/kceo_glossary
site_author: KCEO
site_description: KCEO

nav:
    - Home: index.md
    - Glossary:
        - Introduction: introduction.md
        - Concepts: concepts.md
        - Dependency Graph: mermaid.md
        - Topology: glossary_topology.md
        - Tags: tags.md
        - Terms:
            - Observation: observation.md
            - In-Situ Observation: in-situ_observation.md
            - Entity: entity.md
            - Information: information.md
            - Location: location.md
            - Measurement: measurement.md
            - Measurand: measurand.md
            - Uncertainty: uncertainty.md
            - Object: object.md
            - Period Identifier: period_identifier.md
            - Phenomenon: phenomenon.md
            - Place: place.md
            - Position: position.md
            - Property: property.md
            - Quantity: quantity.md
            - Reference: reference.md
            - Remote Sensing: remote_sensing.md
            - Representativeness: representativeness.md
            - Sample: sample.md
            - Sensor: sensor.md
            - Copernicus Service Provider: copernicus_service_provider.md
            - Expanded Uncertainty: expanded_uncertainty.md
            - Standard Uncertainty: standard_uncertainty.md
            - Trait: trait.md
            - User: user.md
            - Validation: validation.md
            - Verification: verification.md
            - Ancillary data: ancillary_data.md
            - Area of interest: area_of_interest.md
            - Auxiliary data: auxiliary_data.md
            - Band central wavelength: band_central_wavelength.md
            - Baseline: baseline.md
            - Calibration: calibration.md
            - Cell: cell.md
            - Characteristic: characteristic.md
            - Classification system: classification_system.md
            - Classification system levels: classification_system_levels.md
            - Climate projection: climate_projection.md
            - Confidence interval: confidence_interval.md
            - Coverage interval: coverage_interval.md
            - Data: data.md
            - Data access: data_access.md
            - Data format: data_format.md
            - Data licencing: data_licencing.md
            - Duration: duration.md
            - Dwell time: dwell_time.md
            - Earth Observation based output: earth_observation_based_output.md
            - Earth Observation product: earth_observation_product.md
            - Earth Spheres: earth_spheres.md
            - Earth observation: earth_observation.md
            - Environmental Process: environmental_process.md
            - Feature: feature.md
            - Forecast range: forecast_range.md
            - Geocoding: geocoding.md
            - Geographic coordinate reference system: geographic_coordinate_reference_system.md
            - Geographic data: geographic_data.md
            - Geographic grid: geographic_grid.md
            - Geographic identifier: geographic_identifier.md
            - Geolocating: geolocating.md
            - Geolocation information: geolocation_information.md
            - Geopositioning: geopositioning.md
            - Georectifying: georectifying.md
            - Geospatial data: geospatial_data.md
            - Grid: grid.md
            - Impact: impact.md
            - Laboratory observation: laboratory_observation.md
            - Latency: latency.md
            - Location error: location_error.md
            - Measurement uncertainty: measurement_uncertainty.md
            - Minimum Mapping Unit: minimum_mapping_unit.md
            - Minimum Mapping Width: minimum_mapping_width.md
            - Model: model.md
            - Outcome: outcome.md
            - Path: path.md
            - Period: period.md
            - Policy: policy.md
            - Policy cycle: policy_cycle.md
            - Policy file: policy_file.md
            - Policy making: policy_making.md
            - Policy milestone: policy_milestone.md
            - Policy objective: policy_objective.md
            - Policy target: policy_target.md
            - Quality indicator: quality_indicator.md
            - Replicability: replicability.md
            - Reproducibility: reproducibility.md
            - Spatial completeness: spatial_completeness.md
            - Spatial consistency: spatial_consistency.md
            - Spatial extent: spatial_extent.md
            - Spatial reporting unit: spatial_reporting_unit.md
            - Spatial resolution: spatial_resolution.md
            - Spectral Bandwidth: spectral_bandwidth.md
            - Spectral band: spectral_band.md
            - Spectral resolution: spectral_resolution.md
            - Stability: stability.md
            - Temporal consistency: temporal_consistency.md
            - Temporal extent: temporal_extent.md
            - Temporal reporting period: temporal_reporting_period.md
            - Temporal resolution: temporal_resolution.md
            - Temporal revisit: temporal_revisit.md
            - Thematic resolution: thematic_resolution.md
            - Thematic uncertainty: thematic_uncertainty.md
            - Time of day: time_of_day.md
            - Time of year: time_of_year.md
            - Timeliness: timeliness.md
            - Traceability: traceability.md
            - Update frequency: update_frequency.md
            - User Interface: user_interface.md
            - Value: value.md
            - Vertical levels: vertical_levels.md

    - Changelog: changelog.md
    - Blog:
      - blog/index.md
    - Contact: impressum.md

theme:
  name: material
  custom_dir: docs/theme_override_home/
  # 404 page
  static_templates:
    - 404.html
  # enable light/dark mode
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.footer
    - navigation.expand
    - content.action.edit
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    - navigation.instant
    
  font: false
  icon:  # from .icons path. Add to theme override for custom logo.
    logo: earth  # top left header logo
    repo: fontawesome/brands/git-alt
    edit: material/file-edit-outline
  favicon: assets/favicon.ico # browser tab logo

extra_javascript:
        - stylesheets/extra.js
        - stylesheets/tablesort.min.js
        - stylesheets/tablesort.js
extra_css:
        - stylesheets/extra.css
        - stylesheets/font-awesome-4.7.0/css/font-awesome.min.css

repo_url: https://github.com/do-me/kceo_glossary
repo_name: do-me/kceo_glossary
edit_uri: ./edit/main/docs

markdown_extensions:
  - attr_list
  - md_in_html # enable lazy loading images via ![!](assets/test.jpg){ loading=lazy }
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - markdown.extensions.toc:
      baselevel: 1
      permalink: true
  - toc:
      title: Table of Contents
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: do-me/kceo_glossary
      branch: main
      enabled: !ENV [CI, false]
  - tags:
      tags_file: tags.md
  - glightbox
  - blog
  - social
  - privacy
