name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
          
      - run: pip install "mkdocs-material[imaging]==9.5.18"
      - run: pip install mkdocs-glightbox mkdocs-minify-plugin
      - run: mkdocs gh-deploy --force
          
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install
      - run: npm i gzipper -g

      - name: Check out gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          
      - name: Compress all files
        run: gzipper compress --include htm,html,css,js,svg,xml,map,json,img,png,jpg,jpeg --zopfli --brotli --remove-larger .

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Compress Files
          branch: gh-pages
          token: ${{ secrets.SECRET_TOKEN }}
          push_options: '--force'
