name: ci
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false # Disable default credentials
          token: ${{ secrets.SECRET_TOKEN }} # Use the custom token

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install MkDocs and Plugins
        run: |
          pip install "mkdocs-material[imaging]==9.5.18"
          pip install mkdocs-glightbox mkdocs-minify-plugin

      - name: Deploy with MkDocs
        run: mkdocs gh-deploy --force

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Node.js Dependencies
        run: npm install

      - name: Install Gzipper Globally
        run: npm i gzipper -g

      - name: Checkout gh-pages Branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          persist-credentials: false # Disable default credentials
          token: ${{ secrets.SECRET_TOKEN }} # Use the custom token

      - name: Compress Files
        run: gzipper compress --include htm,html,css,js,svg,xml,map,json,img,png,jpg,jpeg --zopfli --brotli --remove-larger .

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Compress Files
          branch: gh-pages
          token: ${{ secrets.SECRET_TOKEN }}
          push_options: '--force'
